In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
dataset = pd.read_csv('Emotify/data.csv')
dataset.head()

,track id,genre,amazement,solemnity,tenderness,nostalgia,calmness,power,joyful_activation,tension,sadness,mood,liked,disliked,age,gender,mother tongue
0,1,classical,0,1,0,0,0,0,1,1,0,3,1,0,21,1,English
1,1,classical,0,0,0,1,0,0,0,0,0,3,0,1,41,1,Dutch
2,1,classical,0,0,0,1,0,0,0,0,1,3,0,0,24,1,English
3,1,classical,0,0,0,0,1,0,0,0,0,3,0,0,32,0,Spanish
4,1,classical,0,0,0,1,1,0,0,0,0,4,0,1,21,0,English

In [5]:
dataset.columns

Index(['track id', ' genre', ' amazement', ' solemnity', ' tenderness',
       ' nostalgia', ' calmness', ' power', ' joyful_activation', ' tension',
       ' sadness', ' mood', ' liked', ' disliked', ' age', ' gender',
       ' mother tongue'],
      dtype='object')

In [6]:
dataset.columns = dataset.columns.str.strip()

In [7]:
gems_annotations = ['amazement', 'solemnity', 'tenderness', 
                    'nostalgia', 'calmness', 'power', 
                    'joyful_activation', 'tension', 'sadness']
print(dataset['genre'].unique())
print(dataset[gems_annotations])

['classical' 'rock' 'electronic' 'pop']
      amazement  solemnity  tenderness  nostalgia  calmness  power  \
0             0          1           0          0         0      0
1             0          0           0          1         0      0
2             0          0           0          1         0      0
3             0          0           0          0         1      0
4             0          0           0          1         1      0
...         ...        ...         ...        ...       ...    ...
8402          1          1           0          0         0      0
8403          0          0           0          1         0      0
8404          0          0           0          0         0      0
8405          1          0           0          0         0      0
8406          1          0           0          0         0      0

      joyful_activation  tension  sadness
0                     1        1        0
1                     0        0        0
2                     0        0        1
3                     0        0        0
4                     0        0        0
...                 ...      ...      ...
8402                  1        0        0
8403                  1        0        1
8404                  0        1        0
8405                  1        1        0
8406                  0        1        0

[8407 rows x 9 columns]

In [8]:
dataset[gems_annotations].dtypes

amazement            int64
solemnity            int64
tenderness           int64
nostalgia            int64
calmness             int64
power                int64
joyful_activation    int64
tension              int64
sadness              int64
dtype: object

In [9]:
# Group by track ID and genre, summing up the GEMS values
data = dataset.groupby(["track id", "genre"])[gems_annotations].sum().reset_index()

# Compute the count per group
count = dataset.groupby(["track id", "genre"]).size().reset_index(name="count")

# Merge count into the summed data
data = data.merge(count, on=["track id", "genre"], how="left")

data.to_csv("Emotify/summed_emotify.csv", index=False)  # Saves without the index column

In [10]:
def softmax(x):
    exp_x = np.exp(x - np.max(x))  # Subtract max for numerical stability
    return exp_x / np.sum(exp_x)
data.head()

,track id,genre,amazement,solemnity,tenderness,nostalgia,calmness,power,joyful_activation,tension,sadness,count
0,1,classical,7,16,10,14,30,1,4,3,15,48
1,2,classical,5,8,20,16,35,2,1,1,5,47
2,3,classical,8,16,6,8,3,13,19,11,7,46
3,4,classical,5,6,22,19,32,1,0,1,6,42
4,5,classical,2,13,14,23,14,2,3,8,14,44

In [11]:
for index, row in data.iterrows():
    print(f"Row {index}: {row['track id']} - {row['genre']} - {row[gems_annotations].values}")
    # Using np.float64 ensures higher numerical stability in the softmax function, especially when dealing with exponentiation
    data_row = np.array(row[gems_annotations].values, dtype=np.float64) / row["count"]
    softmax_values = softmax(data_row)
    print("Data Divided", data_row)
    threshold = int(np.ceil((np.std(data_row) * 10)))
    print("Standard Deviation", threshold)
    # print("Data Softmax", softmax_values)
    
    # Find the threshold value (the Nth largest value)
    top_nth_value = np.partition(data_row, -threshold)[-threshold]  # Gets the Nth largest value

    # Create a binary mask: 1 for values ≥ top_nth_value, 0 otherwise
    binary_arr = (data_row >= top_nth_value).astype(int)

    print(binary_arr)  # Example output: [0 0 0 1 1 1]
    
    data.loc[index, gems_annotations] = binary_arr
    
    print("-" * 100)
    # for col, value in row[gems_annotations].items():
    #     print(data.at[index, col])

Row 0: 1 - classical - [7 16 10 14 30 1 4 3 15]
Data Divided [0.14583333 0.33333333 0.20833333 0.29166667 0.625      0.02083333
 0.08333333 0.0625     0.3125    ]
Standard Deviation 2
[0 1 0 0 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 1: 2 - classical - [5 8 20 16 35 2 1 1 5]
Data Divided [0.10638298 0.17021277 0.42553191 0.34042553 0.74468085 0.04255319
 0.0212766  0.0212766  0.10638298]
Standard Deviation 3
[0 0 1 1 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 2: 3 - classical - [8 16 6 8 3 13 19 11 7]
Data Divided [0.17391304 0.34782609 0.13043478 0.17391304 0.06521739 0.2826087
 0.41304348 0.23913043 0.15217391]
Standard Deviation 2
[0 1 0 0 0 0 1 0 0]
----------------------------------------------------------------------------------------------------
Row 3: 4 - classical - [5 6 22 19 32 1 0 1 6]
Data Divided [0.11904762 0.14285714 0.52380952 0.45238095 0.76190476 0.02380952
 0.         0.02380952 0.14285714]
Standard Deviation 3
[0 0 1 1 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 4: 5 - classical - [2 13 14 23 14 2 3 8 14]
Data Divided [0.04545455 0.29545455 0.31818182 0.52272727 0.31818182 0.04545455
 0.06818182 0.18181818 0.31818182]
Standard Deviation 2
[0 0 1 1 1 0 0 0 1]
----------------------------------------------------------------------------------------------------
Row 5: 6 - classical - [5 10 10 14 26 3 11 6 6]
Data Divided [0.10638298 0.21276596 0.21276596 0.29787234 0.55319149 0.06382979
 0.23404255 0.12765957 0.12765957]
Standard Deviation 2
[0 0 0 1 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 6: 7 - classical - [16 4 7 4 5 10 38 7 1]
Data Divided [0.34042553 0.08510638 0.14893617 0.08510638 0.10638298 0.21276596
 0.80851064 0.14893617 0.0212766 ]
Standard Deviation 3
[1 0 0 0 0 1 1 0 0]
----------------------------------------------------------------------------------------------------
Row 7: 8 - classical - [4 13 15 14 22 2 9 7 7]
Data Divided [0.08695652 0.2826087  0.32608696 0.30434783 0.47826087 0.04347826
 0.19565217 0.15217391 0.15217391]
Standard Deviation 2
[0 0 1 0 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 8: 9 - classical - [5 12 14 18 21 2 3 1 16]
Data Divided [0.11363636 0.27272727 0.31818182 0.40909091 0.47727273 0.04545455
 0.06818182 0.02272727 0.36363636]
Standard Deviation 2
[0 0 0 1 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 9: 10 - classical - [13 10 1 2 1 24 30 10 1]
Data Divided [0.27659574 0.21276596 0.0212766  0.04255319 0.0212766  0.5106383
 0.63829787 0.21276596 0.0212766 ]
Standard Deviation 3
[1 0 0 0 0 1 1 0 0]
----------------------------------------------------------------------------------------------------
Row 10: 11 - classical - [2 14 11 18 17 2 3 6 18]
Data Divided [0.04255319 0.29787234 0.23404255 0.38297872 0.36170213 0.04255319
 0.06382979 0.12765957 0.38297872]
Standard Deviation 2
[0 0 0 1 0 0 0 0 1]
----------------------------------------------------------------------------------------------------
Row 11: 12 - classical - [16 3 8 8 8 4 38 4 2]
Data Divided [0.31372549 0.05882353 0.15686275 0.15686275 0.15686275 0.07843137
 0.74509804 0.07843137 0.03921569]
Standard Deviation 3
[1 0 1 1 1 0 1 0 0]
----------------------------------------------------------------------------------------------------
Row 12: 13 - classical - [1 15 7 19 18 7 1 11 12]
Data Divided [0.0212766  0.31914894 0.14893617 0.40425532 0.38297872 0.14893617
 0.0212766  0.23404255 0.25531915]
Standard Deviation 2
[0 0 0 1 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 13: 14 - classical - [6 10 15 16 19 4 7 8 6]
Data Divided [0.12244898 0.20408163 0.30612245 0.32653061 0.3877551  0.08163265
 0.14285714 0.16326531 0.12244898]
Standard Deviation 2
[0 0 0 1 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 14: 15 - classical - [3 15 13 20 16 1 1 4 20]
Data Divided [0.06818182 0.34090909 0.29545455 0.45454545 0.36363636 0.02272727
 0.02272727 0.09090909 0.45454545]
Standard Deviation 2
[0 0 0 1 0 0 0 0 1]
----------------------------------------------------------------------------------------------------
Row 15: 16 - classical - [4 12 2 2 1 31 5 28 6]
Data Divided [0.09090909 0.27272727 0.04545455 0.04545455 0.02272727 0.70454545
 0.11363636 0.63636364 0.13636364]
Standard Deviation 3
[0 1 0 0 0 1 0 1 0]
----------------------------------------------------------------------------------------------------
Row 16: 17 - classical - [4 7 25 19 28 0 0 2 8]
Data Divided [0.1025641  0.17948718 0.64102564 0.48717949 0.71794872 0.
 0.         0.05128205 0.20512821]
Standard Deviation 3
[0 0 1 1 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 17: 18 - classical - [19 9 3 6 6 5 41 2 0]
Data Divided [0.37254902 0.17647059 0.05882353 0.11764706 0.11764706 0.09803922
 0.80392157 0.03921569 0.        ]
Standard Deviation 3
[1 1 0 0 0 0 1 0 0]
----------------------------------------------------------------------------------------------------
Row 18: 19 - classical - [5 16 16 13 22 2 2 5 10]
Data Divided [0.10638298 0.34042553 0.34042553 0.27659574 0.46808511 0.04255319
 0.04255319 0.10638298 0.21276596]
Standard Deviation 2
[0 1 1 0 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 19: 20 - classical - [4 19 7 14 23 2 3 9 13]
Data Divided [0.08888889 0.42222222 0.15555556 0.31111111 0.51111111 0.04444444
 0.06666667 0.2        0.28888889]
Standard Deviation 2
[0 1 0 0 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 20: 21 - classical - [7 10 18 12 28 1 9 2 4]
Data Divided [0.15555556 0.22222222 0.4        0.26666667 0.62222222 0.02222222
 0.2        0.04444444 0.08888889]
Standard Deviation 2
[0 0 1 0 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 21: 22 - classical - [9 12 20 5 18 3 17 4 3]
Data Divided [0.225 0.3   0.5   0.125 0.45  0.075 0.425 0.1   0.075]
Standard Deviation 2
[0 0 1 0 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 22: 23 - classical - [7 22 2 4 2 17 28 5 4]
Data Divided [0.15217391 0.47826087 0.04347826 0.08695652 0.04347826 0.36956522
 0.60869565 0.10869565 0.08695652]
Standard Deviation 2
[0 1 0 0 0 0 1 0 0]
----------------------------------------------------------------------------------------------------
Row 23: 24 - classical - [5 11 0 0 4 21 27 20 4]
Data Divided [0.10204082 0.2244898  0.         0.         0.08163265 0.42857143
 0.55102041 0.40816327 0.08163265]
Standard Deviation 2
[0 0 0 0 0 1 1 0 0]
----------------------------------------------------------------------------------------------------
Row 24: 25 - classical - [9 21 7 12 12 2 11 10 7]
Data Divided [0.19565217 0.45652174 0.15217391 0.26086957 0.26086957 0.04347826
 0.23913043 0.2173913  0.15217391]
Standard Deviation 2
[0 1 0 1 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 25: 26 - classical - [12 12 1 9 1 15 29 10 3]
Data Divided [0.27272727 0.27272727 0.02272727 0.20454545 0.02272727 0.34090909
 0.65909091 0.22727273 0.06818182]
Standard Deviation 2
[0 0 0 0 0 1 1 0 0]
----------------------------------------------------------------------------------------------------
Row 26: 27 - classical - [4 28 0 2 1 30 2 16 8]
Data Divided [0.1   0.7   0.    0.05  0.025 0.75  0.05  0.4   0.2  ]
Standard Deviation 3
[0 1 0 0 0 1 0 1 0]
----------------------------------------------------------------------------------------------------
Row 27: 28 - classical - [16 4 13 3 21 0 34 2 0]
Data Divided [0.2962963  0.07407407 0.24074074 0.05555556 0.38888889 0.
 0.62962963 0.03703704 0.        ]
Standard Deviation 3
[1 0 0 0 1 0 1 0 0]
----------------------------------------------------------------------------------------------------
Row 28: 29 - classical - [7 13 13 13 20 1 6 4 16]
Data Divided [0.14583333 0.27083333 0.27083333 0.27083333 0.41666667 0.02083333
 0.125      0.08333333 0.33333333]
Standard Deviation 2
[0 0 0 0 1 0 0 0 1]
----------------------------------------------------------------------------------------------------
Row 29: 30 - classical - [22 17 1 1 5 19 26 1 0]
Data Divided [0.47826087 0.36956522 0.02173913 0.02173913 0.10869565 0.41304348
 0.56521739 0.02173913 0.        ]
Standard Deviation 3
[1 0 0 0 0 1 1 0 0]
----------------------------------------------------------------------------------------------------
Row 30: 31 - classical - [4 9 13 24 23 2 1 4 12]
Data Divided [0.08510638 0.19148936 0.27659574 0.5106383  0.4893617  0.04255319
 0.0212766  0.08510638 0.25531915]
Standard Deviation 2
[0 0 0 1 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 31: 32 - classical - [3 10 9 16 19 1 5 2 13]
Data Divided [0.06818182 0.22727273 0.20454545 0.36363636 0.43181818 0.02272727
 0.11363636 0.04545455 0.29545455]
Standard Deviation 2
[0 0 0 1 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 32: 33 - classical - [0 5 12 12 23 0 2 2 11]
Data Divided [0.         0.14285714 0.34285714 0.34285714 0.65714286 0.
 0.05714286 0.05714286 0.31428571]
Standard Deviation 3
[0 0 1 1 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 33: 34 - classical - [6 3 3 3 7 1 16 2 1]
Data Divided [0.24 0.12 0.12 0.12 0.28 0.04 0.64 0.08 0.04]
Standard Deviation 2
[0 0 0 0 1 0 1 0 0]
----------------------------------------------------------------------------------------------------
Row 34: 35 - classical - [2 1 4 3 12 0 1 2 3]
Data Divided [0.11764706 0.05882353 0.23529412 0.17647059 0.70588235 0.
 0.05882353 0.11764706 0.17647059]
Standard Deviation 2
[0 0 1 0 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 35: 36 - classical - [2 2 5 6 9 2 0 3 3]
Data Divided [0.11764706 0.11764706 0.29411765 0.35294118 0.52941176 0.11764706
 0.         0.17647059 0.17647059]
Standard Deviation 2
[0 0 0 1 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 36: 37 - classical - [3 4 8 6 6 1 0 4 5]
Data Divided [0.16666667 0.22222222 0.44444444 0.33333333 0.33333333 0.05555556
 0.         0.22222222 0.27777778]
Standard Deviation 2
[0 0 1 1 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 37: 38 - classical - [1 4 5 6 9 0 1 1 6]
Data Divided [0.05882353 0.23529412 0.29411765 0.35294118 0.52941176 0.
 0.05882353 0.05882353 0.35294118]
Standard Deviation 2
[0 0 0 1 1 0 0 0 1]
----------------------------------------------------------------------------------------------------
Row 38: 39 - classical - [10 5 0 0 0 9 12 3 0]
Data Divided [0.52631579 0.26315789 0.         0.         0.         0.47368421
 0.63157895 0.15789474 0.        ]
Standard Deviation 3
[1 0 0 0 0 1 1 0 0]
----------------------------------------------------------------------------------------------------
Row 39: 40 - classical - [5 5 0 1 0 8 10 6 0]
Data Divided [0.29411765 0.29411765 0.         0.05882353 0.         0.47058824
 0.58823529 0.35294118 0.        ]
Standard Deviation 3
[0 0 0 0 0 1 1 1 0]
----------------------------------------------------------------------------------------------------
Row 40: 41 - classical - [3 7 4 6 6 1 3 2 3]
Data Divided [0.15789474 0.36842105 0.21052632 0.31578947 0.31578947 0.05263158
 0.15789474 0.10526316 0.15789474]
Standard Deviation 2
[0 1 0 1 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 41: 42 - classical - [3 3 4 3 11 2 0 2 2]
Data Divided [0.17647059 0.17647059 0.23529412 0.17647059 0.64705882 0.11764706
 0.         0.11764706 0.11764706]
Standard Deviation 2
[0 0 1 0 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 42: 43 - classical - [4 4 3 4 1 3 5 4 5]
Data Divided [0.23529412 0.23529412 0.17647059 0.23529412 0.05882353 0.17647059
 0.29411765 0.23529412 0.29411765]
Standard Deviation 1
[0 0 0 0 0 0 1 0 1]
----------------------------------------------------------------------------------------------------
Row 43: 44 - classical - [3 6 4 3 8 2 4 1 3]
Data Divided [0.17647059 0.35294118 0.23529412 0.17647059 0.47058824 0.11764706
 0.23529412 0.05882353 0.17647059]
Standard Deviation 2
[0 1 0 0 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 44: 45 - classical - [1 4 3 7 9 1 1 1 9]
Data Divided [0.05882353 0.23529412 0.17647059 0.41176471 0.52941176 0.05882353
 0.05882353 0.05882353 0.52941176]
Standard Deviation 2
[0 0 0 0 1 0 0 0 1]
----------------------------------------------------------------------------------------------------
Row 45: 46 - classical - [3 2 8 7 9 0 1 0 2]
Data Divided [0.17647059 0.11764706 0.47058824 0.41176471 0.52941176 0.
 0.05882353 0.         0.11764706]
Standard Deviation 2
[0 0 1 0 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 46: 47 - classical - [1 3 4 8 7 1 1 2 11]
Data Divided [0.05882353 0.17647059 0.23529412 0.47058824 0.41176471 0.05882353
 0.05882353 0.11764706 0.64705882]
Standard Deviation 3
[0 0 0 1 1 0 0 0 1]
----------------------------------------------------------------------------------------------------
Row 47: 48 - classical - [1 8 1 6 4 1 2 6 5]
Data Divided [0.05882353 0.47058824 0.05882353 0.35294118 0.23529412 0.05882353
 0.11764706 0.35294118 0.29411765]
Standard Deviation 2
[0 1 0 1 0 0 0 1 0]
----------------------------------------------------------------------------------------------------
Row 48: 49 - classical - [0 10 2 2 2 5 1 8 11]
Data Divided [0.         0.58823529 0.11764706 0.11764706 0.11764706 0.29411765
 0.05882353 0.47058824 0.64705882]
Standard Deviation 3
[0 1 0 0 0 0 0 1 1]
----------------------------------------------------------------------------------------------------
Row 49: 50 - classical - [5 6 3 2 0 6 12 5 1]
Data Divided [0.29411765 0.35294118 0.17647059 0.11764706 0.         0.35294118
 0.70588235 0.29411765 0.05882353]
Standard Deviation 2
[0 1 0 0 0 1 1 0 0]
----------------------------------------------------------------------------------------------------
Row 50: 51 - classical - [2 3 4 12 6 0 0 2 7]
Data Divided [0.11111111 0.16666667 0.22222222 0.66666667 0.33333333 0.
 0.         0.11111111 0.38888889]
Standard Deviation 3
[0 0 0 1 1 0 0 0 1]
----------------------------------------------------------------------------------------------------
Row 51: 52 - classical - [4 6 1 1 1 4 9 7 1]
Data Divided [0.22222222 0.33333333 0.05555556 0.05555556 0.05555556 0.22222222
 0.5        0.38888889 0.05555556]
Standard Deviation 2
[0 0 0 0 0 0 1 1 0]
----------------------------------------------------------------------------------------------------
Row 52: 53 - classical - [4 6 0 3 0 5 6 12 2]
Data Divided [0.23529412 0.35294118 0.         0.17647059 0.         0.29411765
 0.35294118 0.70588235 0.11764706]
Standard Deviation 3
[0 1 0 0 0 0 1 1 0]
----------------------------------------------------------------------------------------------------
Row 53: 54 - classical - [3 3 3 0 8 5 15 2 2]
Data Divided [0.16666667 0.16666667 0.16666667 0.         0.44444444 0.27777778
 0.83333333 0.11111111 0.11111111]
Standard Deviation 3
[0 0 0 0 1 1 1 0 0]
----------------------------------------------------------------------------------------------------
Row 54: 55 - classical - [2 1 7 2 10 1 4 5 3]
Data Divided [0.11111111 0.05555556 0.38888889 0.11111111 0.55555556 0.05555556
 0.22222222 0.27777778 0.16666667]
Standard Deviation 2
[0 0 1 0 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 55: 56 - classical - [3 3 6 5 13 1 2 0 3]
Data Divided [0.16666667 0.16666667 0.33333333 0.27777778 0.72222222 0.05555556
 0.11111111 0.         0.16666667]
Standard Deviation 3
[0 0 1 1 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 56: 57 - classical - [4 12 4 2 2 1 1 4 7]
Data Divided [0.22222222 0.66666667 0.22222222 0.11111111 0.11111111 0.05555556
 0.05555556 0.22222222 0.38888889]
Standard Deviation 2
[0 1 0 0 0 0 0 0 1]
----------------------------------------------------------------------------------------------------
Row 57: 58 - classical - [1 6 2 3 2 8 3 8 4]
Data Divided [0.05882353 0.35294118 0.11764706 0.17647059 0.11764706 0.47058824
 0.17647059 0.47058824 0.23529412]
Standard Deviation 2
[0 0 0 0 0 1 0 1 0]
----------------------------------------------------------------------------------------------------
Row 58: 59 - classical - [4 4 0 2 0 8 10 5 2]
Data Divided [0.23529412 0.23529412 0.         0.11764706 0.         0.47058824
 0.58823529 0.29411765 0.11764706]
Standard Deviation 2
[0 0 0 0 0 1 1 0 0]
----------------------------------------------------------------------------------------------------
Row 59: 60 - classical - [2 5 5 9 9 0 0 2 9]
Data Divided [0.11764706 0.29411765 0.29411765 0.52941176 0.52941176 0.
 0.         0.11764706 0.52941176]
Standard Deviation 3
[0 0 0 1 1 0 0 0 1]
----------------------------------------------------------------------------------------------------
Row 60: 61 - classical - [3 3 0 3 3 1 10 6 2]
Data Divided [0.16666667 0.16666667 0.         0.16666667 0.16666667 0.05555556
 0.55555556 0.33333333 0.11111111]
Standard Deviation 2
[0 0 0 0 0 0 1 1 0]
----------------------------------------------------------------------------------------------------
Row 61: 62 - classical - [3 0 2 4 0 2 13 5 0]
Data Divided [0.17647059 0.         0.11764706 0.23529412 0.         0.11764706
 0.76470588 0.29411765 0.        ]
Standard Deviation 3
[0 0 0 1 0 0 1 1 0]
----------------------------------------------------------------------------------------------------
Row 62: 63 - classical - [1 5 4 7 8 0 0 3 5]
Data Divided [0.05882353 0.29411765 0.23529412 0.41176471 0.47058824 0.
 0.         0.17647059 0.29411765]
Standard Deviation 2
[0 0 0 1 1 0 0 0 0]
----------------------------------------------------------------------------------------------------
Row 63: 64 - classical - [4 1 1 1 4 2 10 4 0]
Data Divided [0.23529412 0.05882353 0.05882353 0.05882353 0.23529412 0.11764706
 0.58823529 0.23529412 0.        ]
Standard Deviation 2
[1 0 0 0 1 0 1 1 0]
----------------------------------------------------------------------------------------------------
Row 64: 65 - classical - [4 1 0 0 0 5 12 5 0]
Data Divided [0.23529412 0.05882353 0.         0.         0.         0.29411765
 0.70588235 0.29411765 0.        ]
Standard Deviation 3
[0 0 0 0 0 1 1 1 0]
----------------------------------------------------------------------------------------------------
Row 65: 66 - classical - [2 4 0 3 1 3 4 8 1]
Data Divided [0.11764706 0.23529412 0.         0.17647059 0.05882353 0.17647059
 0.23529412 0.47058824 0.05882353]
Standard Deviation 2
[0 1 0 0 0 0 1 1 0]
----------------------------------------------------------------------------------------------------
Row 66: 67 - classical - [3 3 5 1 8 2 4 4 1]
Data Divided [0.17647059 0.17647059 0.29411765 0.05882353 0.47058824 0.11764706

In [12]:
data.to_csv("Emotify/multi_hot_encoded_emotify.csv", index=False)  # Saves without the index column